-- polecenie generujace tabele select GET_DDL('table', 'B_CUSTOMER');
-- STAGE_CUSTOMER from SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL.CUSTOMER
create or replace TABLE PUBLIC.STAGE_CUSTOMER (
    C_CUSTOMER_SK NUMBER(38,0),
    C_CUSTOMER_ID VARCHAR(16),
    C_FIRST_NAME VARCHAR(20),
    C_LAST_NAME VARCHAR(30),
    C_PREFERRED_CUST_FLAG VARCHAR(1),
    C_BIRTH_DAY NUMBER(38,0),
    C_BIRTH_MONTH NUMBER(38,0),
    C_BIRTH_YEAR NUMBER(38,0),
    C_BIRTH_COUNTRY VARCHAR(20),
    C_LOGIN VARCHAR(13),
    C_EMAIL_ADDRESS VARCHAR(50),
    C_LAST_REVIEW_DATE VARCHAR(10)
);

-- final table SNOWFLAKE_CUSTOMER
create or replace TABLE PUBLIC.TARGET_CUSTOMER (
    C_CUSTOMER_SK NUMBER(38,0),
    C_CUSTOMER_ID VARCHAR(16),
    C_FIRST_NAME VARCHAR(20),
    C_LAST_NAME VARCHAR(30),
    C_PREFERRED_CUST_FLAG VARCHAR(1),
    C_BIRTH_DAY NUMBER(38,0),
    C_BIRTH_MONTH NUMBER(38,0),
    C_BIRTH_YEAR NUMBER(38,0),
    C_BIRTH_COUNTRY VARCHAR(20),
    C_LOGIN VARCHAR(13),
    C_EMAIL_ADDRESS VARCHAR(50),
    C_LAST_REVIEW_DATE VARCHAR(10),
    C_START_DATE timestamp, 
    C_END_DATE timestamp
);